name: Lepzien2021
channels:
 - bioconda
 - conda-forge
 - defaults
 - r

dependencies:
 - r-base=3.5.1
 - rstudio=1.1.456
 - bioconductor-biomart=2.38.0
 - bioconductor-genomeinfodbdata=1.2.0
 - bioconductor-sva=3.30.1
 - bioconductor-edger=3.24.3
 - bioconductor-preprocesscore=1.44.0
 - bioconductor-edaseq=2.16.0
 - bioconductor-fgsea=1.8.0
 - r-devtools=2.1.0
 - r-biocmanager=1.30
 - r-data.table=1.12.2
 - r-igraph=1.2
 - r-pheatmap=1.0
 - r-rafalib=1.0.0
 - r-rcolorbrewer=1.1
 - r-scales=1.0
 - r-rafalib=1.0.0
 - r-readxl=1.3.1
 - r-beeswarm=0.2.3
 - r-ggplot2=3.1.1
 - r-ggrepel=0.8.0
 - r-enrichR=1.0
 - r-vioplot=0.3.2
 - r-factoextra=1.0.5
 - r-statmod
 - bioconductor-Rgraphviz
 - bioconductor-fgsea
 - r-bcp
